#Example1: The following example uses only one Catch block with the Try block:

Try  
{  
Get-ChildItem  
}  
catch  
{  
"Error in a Try block."  
}  

#Example2: The following example also uses only one Catch block with the Try block:

Try  
{  
Get-Child  
}  
catch  
{  
"Error in a Try block."  
}  